#!/usr/bin/env bash
# runners/create_pr.sh
#
# Creates a GitHub PR with spec summary, evidence, and preview link.
#
# Environment variables:
#   REPO_SLUG       - e.g., "superplanehq/superplane"
#   ISSUE_NUMBER    - Original issue number
#   BRANCH_NAME     - Feature branch
#   SPEC_JSON       - Path to spec JSON
#   PREVIEW_URL     - Render preview URL
#   VERIFY_JSON     - Path to verification result
#   GITHUB_TOKEN    - GitHub PAT
#   WORKDIR         - Working directory

set -euo pipefail

REPO_SLUG="${REPO_SLUG:?REPO_SLUG is required}"
ISSUE_NUMBER="${ISSUE_NUMBER:?ISSUE_NUMBER is required}"
BRANCH_NAME="${BRANCH_NAME:-issueforge/$ISSUE_NUMBER}"
GITHUB_TOKEN="${GITHUB_TOKEN:?GITHUB_TOKEN is required}"
WORKDIR="${WORKDIR:-/tmp/issueforge}"

export GH_TOKEN="$GITHUB_TOKEN"

# Extract spec info
TITLE="[IssueForge] Implement #${ISSUE_NUMBER}"
SUMMARY=""
AC_REPORT=""
IMPL_STEPS=""

if [ -n "${SPEC_JSON:-}" ] && [ -f "$SPEC_JSON" ]; then
    TITLE=$(python3 -c "
import json
spec = json.load(open('$SPEC_JSON'))
print(f\"[IssueForge] {spec.get('title', 'Issue #$ISSUE_NUMBER')}\")" 2>/dev/null || echo "$TITLE")

    SUMMARY=$(python3 -c "
import json
spec = json.load(open('$SPEC_JSON'))
print(spec.get('summary', ''))" 2>/dev/null || echo "")

    AC_REPORT=$(python3 -c "
import json
spec = json.load(open('$SPEC_JSON'))
for ac in spec.get('acceptance_criteria', []):
    print(f\"- {ac['id']}: {ac['description']}\")" 2>/dev/null || echo "")

    IMPL_STEPS=$(python3 -c "
import json
spec = json.load(open('$SPEC_JSON'))
for step in spec.get('implementation_plan', []):
    print(f'- {step}')" 2>/dev/null || echo "")
fi

# Verification status
VERIFY_STATUS="unknown"
VERIFY_ATTEMPTS="?"
if [ -n "${VERIFY_JSON:-}" ] && [ -f "$VERIFY_JSON" ]; then
    VERIFY_STATUS=$(python3 -c "import json; print(json.load(open('$VERIFY_JSON')).get('status','unknown'))" 2>/dev/null || echo "unknown")
    VERIFY_ATTEMPTS=$(python3 -c "import json; print(json.load(open('$VERIFY_JSON')).get('attempts','?'))" 2>/dev/null || echo "?")
fi

PREVIEW_SECTION=""
if [ -n "${PREVIEW_URL:-}" ] && [ "$PREVIEW_URL" != "" ]; then
    PREVIEW_SECTION="### Preview
[Open Render Preview](${PREVIEW_URL})"
fi

# Create PR using gh CLI
echo "=== Creating PR ==="

PR_URL=$(gh pr create \
    --repo "$REPO_SLUG" \
    --head "$BRANCH_NAME" \
    --base "main" \
    --title "$TITLE" \
    --body "## IssueForge — Automated Implementation

Closes #${ISSUE_NUMBER}

### Summary
${SUMMARY}

### Acceptance Criteria
${AC_REPORT}

### Implementation
${IMPL_STEPS}

${PREVIEW_SECTION}

### Verification
- Build: **${VERIFY_STATUS}**
- Repair attempts: ${VERIFY_ATTEMPTS}

---
*Generated by IssueForge — SuperPlane Software Factory*" 2>&1) || {
    echo "PR creation failed, may already exist"
    PR_URL=$(gh pr view "$BRANCH_NAME" --repo "$REPO_SLUG" --json url -q .url 2>/dev/null || echo "unknown")
}

echo "=== PR Created ==="
echo "PR URL: $PR_URL"

PR_NUMBER=$(echo "$PR_URL" | grep -oP '\d+$' || echo "0")

cat > "$WORKDIR/pr_result.json" << ENDJSON
{
    "pr_url": "$PR_URL",
    "pr_number": "$PR_NUMBER",
    "issue_number": $ISSUE_NUMBER
}
ENDJSON
